log-level: ERROR
webhook:
  enabled: env(webhook:false)
  port: env(PORT:8443)
  externalUrl: https://lastkatkabot.herokuapp.com:8443
  internalUrl: https://lastkatkabot.herokuapp.com:8443
  certificatePublicKeyPath: cert/public_cert.pem
  certificateStorePath: cert/keystore.jks
  certificateStorePassword: env(STORE_PASSWORD)
modules:
  - com.senderman.lastkatkabot.LastkatkaBot
