log-level: ERROR
webhook:
  enabled: env(webhook:false)
  port: env(PORT:8443)
  externalUrl: https://lastkatkabot.herokuapp.com
  internalUrl: 0.0.0.0:$port
modules:
  - com.senderman.lastkatkabot.LastkatkaBot
